app_auth/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login',login_blog,name="login-blog"),
    path('register', register, name="register"),
    path('logout', logout_blog, name="logout")
    
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('auth/', include('app_auth.urls')),
    path('my-admin/', include('app_admin.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
      

app_auth/models.py
from django.db import models

# Create your models here.

app_auth/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput (attrs={'class': 'form-control'}))
    pwd = forms.CharField(label="Mot de pass",widget= forms.PasswordInput(attrs={'class':'form-control'}))
    
    
class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput (attrs={'class': 'form-control'}))
    pwd = forms.CharField(label="Mot de pass",widget= forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirm = forms.CharField(label="confirmer mot de passe",widget= forms.PasswordInput(attrs={'class':'form-control'}))

app_auth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *

# Create your views here.
def login_blog(request):
   if request.method == "POST":
       form = LoginForm(request.POST)
       if form.is_valid():
           username= form.cleaned_data ['username']
           pwd = form.cleaned_data ['pwd']
           user=authenticate(username=username, password=pwd)
           if user is not None:
               login(request,user)#permet de stocker l'utilisateur dans request
               return redirect("/checkout")
           else:
               messages.error(request, "authentification invalid")
               return render(request,"login.html",{"form":form}) 
       else: 
           return render(request, "login.html", {"form": form})
               
   else:
       form =LoginForm()
       return render(request,'login.html',{"form":form})
   
   
   
def register(request):
    if request.method == "POST":
        form =RegisterForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            pwd=form.cleaned_data ['pwd']
            if(User.objects.filter(username=username).exists()):
                messages.error(request,"Email ou mot de passe incorrect!! veuillez reessayer svp")
                return render(request, "register.html", {"form": form})
            else:
                User.objects.create_user(username=username,password=pwd)
                return redirect("login-blog")
        else:
            return render(request, "register.html", {"form": form})
        return render(request,"register.html",{})
    form = RegisterForm()
    return render(request,"register.html",{"form":form})

def logout_blog(request):
    logout(request)
    return redirect("login-blog")
    

    
    
    
    
    
    
    
    
    
    
      

app_auth/templates/login.html
  {% extends 'shop/base.html' %}
  {% block content %}
    
    <div class="container">
        <div class="col-md-12 mt-5">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger text-center"> <strong> {{message}}</strong></div>
            {% endfor %}
            {% endif %}
            <form action="" method="POST" novalidate> {% csrf_token %} 
             <div class="card">
            <div class="card-header text-center"><i class="fa-solid fa-user"></i>CONNEXION</div>
                <div class="card-body">
                    <label for="id_username">Nom utilisateur</label>
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    <div><small class="text-danger">{{ error }}</small></div>
                    {% endfor %}
                    {% endif%}
                    {{form.username}}


                     <label for="id_pwd">Mot de passe</label>
                      {% if form.pwd.errors %}
                    {% for error in form.pwd.errors %}
                    <div><small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}
                    {{form.pwd}}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block ">SE CONNECTER </button>
                                         <p class="mt-2"> Si vous n'avez pas encore de compte veuillez creer svp!!<a href="{% url 'register' %}" style="text-decoration:none;"> Creer un compte</a></p>
                     </div>
                     </div>
                    </form>
                </div>
       
             </div>
{% endblock %}

app_auth/templates/register.html
{% extends 'shop/base.html' %}
{% block content %}
    
    <div class="container">
        <div class="col-md-12 mt-5">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger text-center"> <strong> {{message}}</strong></div>
            {% endfor %}
            {% endif %}
            <form action="" method="POST" novalidate> {% csrf_token %} 
             <div class="card">
            <div class="card-header text-center"><i class="fa-solid fa-user-lock"></i>Creation de compte</div>
                <div class="card-body">
                {{ form }}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block "> Creer votre compte ici</button>
                     </div>
                     </div>
                    </form>
                </div>
       
             </div>

   {% endblock %}